services:
  web:
    build:
      context: .
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      # - .:/app
      - hubsnub_data:/app/data
      - hubsnub_static:/app/staticfiles
    environment:
      - SERVICE_FQDN_WEB_8000=https://hubsnub.dgt.is
      - SQLITE_PATH=/app/data/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

volumes:
  hubsnub_data:
  hubsnub_static:
