# Generated by Django 4.2.29 on 2026-03-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        help_text="Full repo name (owner/repo)", max_length=512
                    ),
                ),
                ("thread_number", models.IntegerField(help_text="PR or issue number")),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g., review_requested, mentioned", max_length=100
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("suppress", "Suppress"),
                            ("skip", "Skip"),
                        ],
                        help_text="allow, suppress, or skip",
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Human-readable reason for the decision"
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, help_text="Link to the PR/issue on GitHub"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_requested_direct",
                    models.BooleanField(
                        default=True, help_text="Your PR review is requested personally"
                    ),
                ),
                (
                    "review_requested_team",
                    models.BooleanField(
                        default=False, help_text="Review requests to a team you're on"
                    ),
                ),
                (
                    "pr_approved_or_changes",
                    models.BooleanField(
                        default=True,
                        help_text="Approval/changes requested on PRs you authored",
                    ),
                ),
                (
                    "assigned",
                    models.BooleanField(
                        default=True, help_text="You are assigned to a PR or issue"
                    ),
                ),
                (
                    "comment_on_your_pr",
                    models.BooleanField(
                        default=True, help_text="Comments on PRs you authored"
                    ),
                ),
                (
                    "mentioned",
                    models.BooleanField(default=True, help_text="Direct @mentions"),
                ),
                (
                    "pr_merged",
                    models.BooleanField(
                        default=False, help_text="Merge notifications for your PRs"
                    ),
                ),
                (
                    "pr_failed_checks",
                    models.BooleanField(
                        default=False, help_text="CI failure notifications"
                    ),
                ),
                (
                    "suppress_mode",
                    models.CharField(
                        choices=[
                            ("unsubscribe", "Unsubscribe"),
                            ("ignore", "Ignore (hard mute)"),
                        ],
                        default="unsubscribe",
                        help_text="How to suppress: unsubscribe (can be re-subscribed) or ignore (hard mute)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="WatchedRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(help_text="Org or user name", max_length=255),
                ),
                (
                    "repo",
                    models.CharField(
                        help_text="Repo name, or * for all repos in that org",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether filtering is enabled for this repo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watched Repo",
                "verbose_name_plural": "Watched Repos",
                "unique_together": {("owner", "repo")},
            },
        ),
        migrations.CreateModel(
            name="RepoOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_requested_direct",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "review_requested_team",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "pr_approved_or_changes",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("assigned", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "comment_on_your_pr",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("mentioned", models.BooleanField(blank=True, default=None, null=True)),
                ("pr_merged", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "pr_failed_checks",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "suppress_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unsubscribe", "Unsubscribe"),
                            ("ignore", "Ignore (hard mute)"),
                        ],
                        default=None,
                        help_text="Null = use global default",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "watched_repo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override",
                        to="notifications.watchedrepo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repo Override",
                "verbose_name_plural": "Repo Overrides",
            },
        ),
    ]
